### ISSUE TITLE
Issues using System

### ISSUE THREAD

**Issue by xtechgamer735** [radiocicletta/morganfreeman#12]
Hello!

Running on windows.

I am trying to setup the authentication however I'm running into a few issues. Im using the following command to run the script: `python frosty.py -h http://localhost:8000 -u admin -w password -b 9000 -r Icecast2 Server`

When I do this, I get a -- MARK -- 401 Authentication error however when I change the host to /admin i get a 400 bad request.

Do you know how I can fix this?

Many thanks!

**Comment by leofiore** [comment]
Be sure the realm is passed correctly as one single argument. You probably need to enclose it in quotes or double quotes (like `-r "Icecast2 Server"` or `-r 'Icecast2 Server'`). Keep in mind that the software has never been tested on Windows, although it should run without problems.

**Comment by xtechgamer735** [comment]
Hello!

Thanks for your quick reply! I've tried this and i'm now getting the following error:

2017-04-11 12:29:43,223 __main__     DEBUG    Process starting
2017-04-11 12:29:43,236 __main__     DEBUG    Process started
2017-04-11 12:29:43,236 icecast.daemon DEBUG    Daemon initialized
2017-04-11 12:29:43,535 icecast.daemon DEBUG    StatsCollector initialized
2017-04-11 12:29:43,535 icecast.daemon DEBUG    launched StatsCollector Instance
2017-04-11 12:29:43,542 icecast.daemon DEBUG    HTTP server initialized
2017-04-11 12:29:43,546 icecast.daemon ERROR    Failed update: ''

Failed update: ''
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __boot
    self.run()
  File "C:\Users\Administrator\Desktop\morganfreeman\icest
53, in run
    resultstr = result.read()
AttributeError: 'NoneType' object has no attribute 'read'

Any ideas what might be causing this? Also is it possible to run this from a separate server to the machine that is hosting icecast?

Thanks

**Comment by leofiore** [comment]
Looks like it cannot identify which version of icecast you are using.

When it starts, the software tries to retrieve the page `/server_version.xsl` from your icecast instance. Please check that the specified web page is reachable (e.g. using your browser to visit `http://[your_icecast_server]:[your_icecast_port]/server_version.xsl`). If the page is not available, please check your icecast installation. 

You can run the application on a separate machine too, just be sure the application can reach the icecast server and the icecast's admin section.

Also, if you encounter more problems please provide more details on your installation, especially on your icecast server version.

**Comment by xtechgamer735** [comment]
No issues accessing it from the web! The page loads fine for me. Im using Icecast 2.4.3, are there any more details which would help?

Thanks!

**Comment by leofiore** [comment]
i cannot reproduce the issue with icecast 2.4.3 .

The only thing i can think about this problem is that Windows or some sort of firewall is blocking morganfreeman from connecting to the internet. If you have windows firewall enabled, or some kind of other firewalls running, please check that python.exe is allowed to connect to outside machines.

**Comment by xtechgamer735** [comment]
Must be a windows issue. Tried running it on my linux vps'es (Centos <3) and it works fine! Thank you for your help!
