### ISSUE TITLE
getting errors in console ... Failed update

### ISSUE THREAD

**Issue by romeor** [radiocicletta/morganfreeman#6]
-- MARK --
Failed update: HTTP Error 401: Authentication Required
-- MARK --
Failed update: HTTP Error 401: Authentication Required
-- MARK --
Failed update: HTTP Error 401: Authentication Required

but i'm using the login and password of admin user that works from Web browser

what should I do about them ?

**Comment by leofiore** [comment]
can you please attach the icecast version are you monitoring?

**Comment by romeor** [comment]
Hi,

sure. Its Icecast 2.4.2

**Comment by leofiore** [comment]
Hi,

are you providing the correct realm for the authentication? If you don't know what is the realm of your icecast server, you can identify it by using something like ` curl -s -i  http://stream.priyom.org:8000/admin/ | grep WWW-Authenticate | sed -e 's/.*://' ` via CLI. the resulting string contains the realm that you will specify with the ` -r ` option

`./frosty.py -h <hostname> -u <username> -w <password> -b <bindport> -r <INSERT REALM HERE>  `

**Comment by romeor** [comment]
Hey!

Seems like this way it works. Thanks.

**Comment by leofiore** [comment]
Sweet. I'm closing it and mark it as a consequence of #7 .
